on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1

  bundle:
    runs-on: ubuntu-latest
    needs: [pre-commit]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm -C frontend ci
      - name: Build frontend
        run: npm -C frontend run build -- --emptyOutDir --outDir "$PWD/ticket_queue/frontend"
      - name: Disable custom build hook
        run: |
          rm frontend_build_hook.py
          perl -0777 -i -pe 's/(?ms)\[tool\.hatch\.build\.hooks\.custom\].*?^\n//' pyproject.toml
          ! git diff --exit-code -- pyproject.toml
      - name: Generate frontend package file
        run: |
          >ticket_queue/_packaged_frontend.py cat << EOF
          import os.path

          PACKAGE_DIR = os.path.join(
              os.path.dirname(__file__),
              "frontend"
          )
          EOF
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit changes and push to bundled branch
        run: |
          git fetch origin

          if git ls-remote --exit-code --heads origin bundled >/dev/null; then
            git switch -C bundled --track origin/bundled
          else
            git switch -c bundled
          fi

          git add --all
          if git commit -m "Bundle for ${{ github.sha }}"; then
            git push -u origin bundled
          else
            echo "No changes to commit."
          fi
